[Locations]
# The location of the source
src = "src"
# The location used to store temporary files
tempDir = ".mpt"

[Downloads]
# The maximum number of threads that will be used for downloads
maxThreads = 5
# The timeout of http requests in ms
httpTimeout = 30000
